[2017-10-03 01:44:30 +0000] [40] [INFO] Starting gunicorn 19.7.1
[2017-10-03 01:44:30 +0000] [40] [INFO] Listening at: http://127.0.0.1:8080 (40)
[2017-10-03 01:44:30 +0000] [40] [INFO] Using worker: sync
[2017-10-03 01:44:30 +0000] [51] [INFO] Booting worker with pid: 51
[2017-10-03 02:16:10 +0000] [29] [INFO] Starting gunicorn 19.7.1
[2017-10-03 02:16:10 +0000] [29] [INFO] Listening at: http://127.0.0.1:8080 (29)
[2017-10-03 02:16:10 +0000] [29] [INFO] Using worker: sync
[2017-10-03 02:16:10 +0000] [39] [INFO] Booting worker with pid: 39
[2017-10-03 02:37:45 +0000] [29] [INFO] Starting gunicorn 19.7.1
[2017-10-03 02:37:45 +0000] [29] [INFO] Listening at: http://127.0.0.1:8080 (29)
[2017-10-03 02:37:45 +0000] [29] [INFO] Using worker: sync
[2017-10-03 02:37:45 +0000] [39] [INFO] Booting worker with pid: 39
[2017-10-03 03:02:39 +0000] [29] [INFO] Handling signal: term
[2017-10-03 03:02:41 +0000] [29] [INFO] Shutting down: Master
[2017-10-03 03:04:09 +0000] [29] [INFO] Starting gunicorn 19.7.1
[2017-10-03 03:04:09 +0000] [29] [INFO] Listening at: http://127.0.0.1:8080 (29)
[2017-10-03 03:04:09 +0000] [29] [INFO] Using worker: sync
[2017-10-03 03:04:09 +0000] [39] [INFO] Booting worker with pid: 39
[2017-10-03 04:02:17 +0000] [29] [INFO] Handling signal: term
[2017-10-03 04:02:17 +0000] [29] [INFO] Shutting down: Master
[2017-10-03 04:45:47 +0000] [31] [INFO] Starting gunicorn 19.7.1
[2017-10-03 04:45:47 +0000] [31] [INFO] Listening at: http://127.0.0.1:8080 (31)
[2017-10-03 04:45:47 +0000] [31] [INFO] Using worker: sync
[2017-10-03 04:45:47 +0000] [41] [INFO] Booting worker with pid: 41
[2017-10-03 06:58:47 +0000] [31] [CRITICAL] WORKER TIMEOUT (pid:41)
Exception in thread Thread-1 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/reloader.py", line 42, in run
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/reloader.py", line 30, in get_files
<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'modules'
[2017-10-03 06:58:51 +0000] [49] [INFO] Booting worker with pid: 49
[2017-10-03 08:10:09 +0000] [31] [CRITICAL] WORKER TIMEOUT (pid:49)
Exception in thread Thread-1 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/reloader.py", line 42, in run
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/reloader.py", line 31, in get_files
  File "/usr/lib/python2.7/re.py", line 155, in sub
  File "/usr/lib/python2.7/re.py", line 237, in _compile
<type 'exceptions.TypeError'>: 'NoneType' object has no attribute '__getitem__'
[2017-10-03 08:10:09 +0000] [55] [INFO] Booting worker with pid: 55
2017-10-03 09:25:22,084 [MainThread:140021097748224] [django.request:182] [base:get_response] [WARNING]- Not Found: /home
2017-10-03 09:26:01,990 [MainThread:140021097748224] [django.request:182] [base:get_response] [WARNING]- Not Found: /home
[2017-10-03 09:48:20 +0000] [29] [INFO] Starting gunicorn 19.7.1
[2017-10-03 09:48:20 +0000] [29] [INFO] Listening at: http://127.0.0.1:8080 (29)
[2017-10-03 09:48:20 +0000] [29] [INFO] Using worker: sync
[2017-10-03 09:48:20 +0000] [39] [INFO] Booting worker with pid: 39
[2017-10-03 10:17:00 +0000] [29] [INFO] Starting gunicorn 19.7.1
[2017-10-03 10:17:00 +0000] [29] [INFO] Listening at: http://127.0.0.1:8080 (29)
[2017-10-03 10:17:00 +0000] [29] [INFO] Using worker: sync
[2017-10-03 10:17:00 +0000] [39] [INFO] Booting worker with pid: 39
2017-10-03 10:36:15,779 [MainThread:139686460434176] [django.request:182] [base:get_response] [WARNING]- Not Found: /favicon.ico
[2017-10-03 12:54:37 +0000] [29] [CRITICAL] WORKER TIMEOUT (pid:39)
Exception in thread Thread-1 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/reloader.py", line 42, in run
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/reloader.py", line 30, in get_files
<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'modules'
[2017-10-03 12:54:39 +0000] [47] [INFO] Booting worker with pid: 47
[2017-10-04 01:42:25 +0000] [29] [CRITICAL] WORKER TIMEOUT (pid:47)
[2017-10-04 01:42:49 +0000] [51] [INFO] Booting worker with pid: 51
[2017-10-04 01:43:20 +0000] [29] [CRITICAL] WORKER TIMEOUT (pid:51)
[2017-10-04 01:43:21 +0000] [55] [INFO] Booting worker with pid: 55
[2017-10-05 01:39:51 +0000] [29] [CRITICAL] WORKER TIMEOUT (pid:55)
[2017-10-05 01:40:16 +0000] [59] [INFO] Booting worker with pid: 59
[2017-10-05 01:40:46 +0000] [29] [CRITICAL] WORKER TIMEOUT (pid:59)
[2017-10-05 01:40:47 +0000] [63] [INFO] Booting worker with pid: 63
[2017-10-05 03:58:38 +0000] [29] [CRITICAL] WORKER TIMEOUT (pid:63)
[2017-10-05 03:58:40 +0000] [69] [INFO] Booting worker with pid: 69
[2017-10-05 11:29:04 +0000] [29] [CRITICAL] WORKER TIMEOUT (pid:69)
[2017-10-05 11:29:30 +0000] [75] [INFO] Booting worker with pid: 75
[2017-10-05 14:49:27 +0000] [29] [CRITICAL] WORKER TIMEOUT (pid:75)
Exception in thread Thread-1 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/reloader.py", line 42, in run
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/reloader.py", line 30, in get_files
<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'modules'
[2017-10-05 14:49:33 +0000] [79] [INFO] Booting worker with pid: 79
[2017-10-06 01:11:16 +0000] [29] [CRITICAL] WORKER TIMEOUT (pid:79)
[2017-10-06 01:11:19 +0000] [83] [INFO] Booting worker with pid: 83
[2017-10-06 05:00:20 +0000] [29] [CRITICAL] WORKER TIMEOUT (pid:83)
Exception in thread Thread-1 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/reloader.py", line 42, in run
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/reloader.py", line 31, in get_files
<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'sub'
[2017-10-06 05:00:21 +0000] [87] [INFO] Booting worker with pid: 87
[2017-10-06 13:53:00 +0000] [29] [CRITICAL] WORKER TIMEOUT (pid:87)
[2017-10-06 13:53:03 +0000] [91] [INFO] Booting worker with pid: 91
[2017-10-06 21:29:04 +0000] [29] [CRITICAL] WORKER TIMEOUT (pid:91)
[2017-10-06 21:29:04 +0000] [95] [INFO] Booting worker with pid: 95
[2017-10-06 22:47:06 +0000] [29] [CRITICAL] WORKER TIMEOUT (pid:95)
[2017-10-06 22:47:08 +0000] [99] [INFO] Booting worker with pid: 99
[2017-10-07 13:57:17 +0000] [29] [CRITICAL] WORKER TIMEOUT (pid:99)
[2017-10-07 13:57:43 +0000] [103] [INFO] Booting worker with pid: 103
[2017-10-08 01:24:16 +0000] [29] [CRITICAL] WORKER TIMEOUT (pid:103)
[2017-10-08 01:24:23 +0000] [107] [INFO] Booting worker with pid: 107
[2017-10-08 01:24:54 +0000] [29] [CRITICAL] WORKER TIMEOUT (pid:107)
[2017-10-08 01:24:55 +0000] [111] [INFO] Booting worker with pid: 111
[2017-10-08 01:25:26 +0000] [29] [CRITICAL] WORKER TIMEOUT (pid:111)
[2017-10-08 01:25:26 +0000] [111] [INFO] Worker exiting (pid: 111)
[2017-10-08 01:25:27 +0000] [115] [INFO] Booting worker with pid: 115
[2017-10-08 05:15:21 +0000] [29] [CRITICAL] WORKER TIMEOUT (pid:115)
[2017-10-08 05:15:23 +0000] [119] [INFO] Booting worker with pid: 119
[2017-10-08 07:22:35 +0000] [29] [CRITICAL] WORKER TIMEOUT (pid:119)
[2017-10-08 07:22:36 +0000] [123] [INFO] Booting worker with pid: 123
[2017-10-08 11:20:31 +0000] [29] [CRITICAL] WORKER TIMEOUT (pid:123)
[2017-10-08 11:20:33 +0000] [127] [INFO] Booting worker with pid: 127
[2017-10-08 14:20:50 +0000] [29] [CRITICAL] WORKER TIMEOUT (pid:127)
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/reloader.py", line 42, in run
    for filename in self.get_files():
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/reloader.py", line 30, in get_files
    for module in list(sys.modules.values())
AttributeError: 'NoneType' object has no attribute 'modules'

[2017-10-08 14:20:50 +0000] [131] [INFO] Booting worker with pid: 131
[2017-10-08 14:35:09 +0000] [29] [CRITICAL] WORKER TIMEOUT (pid:131)
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/reloader.py", line 42, in run
    for filename in self.get_files():
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/reloader.py", line 30, in get_files
    for module in list(sys.modules.values())
AttributeError: 'NoneType' object has no attribute 'modules'

[2017-10-08 14:35:09 +0000] [135] [INFO] Booting worker with pid: 135
[2017-10-08 19:17:34 +0000] [29] [CRITICAL] WORKER TIMEOUT (pid:135)
[2017-10-08 19:17:34 +0000] [139] [INFO] Booting worker with pid: 139
[2017-10-08 22:20:21 +0000] [29] [CRITICAL] WORKER TIMEOUT (pid:139)
[2017-10-08 22:20:21 +0000] [143] [INFO] Booting worker with pid: 143
[2017-10-09 01:25:53 +0000] [29] [CRITICAL] WORKER TIMEOUT (pid:143)
[2017-10-09 01:25:53 +0000] [147] [INFO] Booting worker with pid: 147
[2017-10-09 02:28:46 +0000] [29] [CRITICAL] WORKER TIMEOUT (pid:147)
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/reloader.py", line 44, in run
    mtime = os.stat(filename).st_mtime
AttributeError: 'NoneType' object has no attribute 'stat'

[2017-10-09 02:28:46 +0000] [151] [INFO] Booting worker with pid: 151
[2017-10-09 04:11:28 +0000] [29] [CRITICAL] WORKER TIMEOUT (pid:151)
[2017-10-09 04:11:28 +0000] [155] [INFO] Booting worker with pid: 155
[2017-10-09 08:44:02 +0000] [29] [CRITICAL] WORKER TIMEOUT (pid:155)
[2017-10-09 08:44:02 +0000] [159] [INFO] Booting worker with pid: 159
[2017-10-09 10:31:21 +0000] [29] [CRITICAL] WORKER TIMEOUT (pid:159)
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/reloader.py", line 42, in run
    for filename in self.get_files():
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/reloader.py", line 31, in get_files
    if hasattr(module, '__file__')
  File "/usr/lib/python2.7/re.py", line 155, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or buffer

[2017-10-09 10:31:21 +0000] [163] [INFO] Booting worker with pid: 163
[2017-10-09 11:31:44 +0000] [29] [CRITICAL] WORKER TIMEOUT (pid:163)
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/reloader.py", line 42, in run
    for filename in self.get_files():
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/reloader.py", line 30, in get_files
    for module in list(sys.modules.values())
AttributeError: 'NoneType' object has no attribute 'modules'

[2017-10-09 11:31:44 +0000] [167] [INFO] Booting worker with pid: 167
[2017-10-09 12:47:28 +0000] [29] [CRITICAL] WORKER TIMEOUT (pid:167)
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/reloader.py", line 42, in run
    for filename in self.get_files():
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/reloader.py", line 30, in get_files
    for module in list(sys.modules.values())
AttributeError: 'NoneType' object has no attribute 'modules'

[2017-10-09 12:47:28 +0000] [171] [INFO] Booting worker with pid: 171
[2017-10-09 16:36:38 +0000] [29] [CRITICAL] WORKER TIMEOUT (pid:171)
[2017-10-09 16:36:42 +0000] [175] [INFO] Booting worker with pid: 175
[2017-10-09 21:39:06 +0000] [29] [CRITICAL] WORKER TIMEOUT (pid:175)
Exception in thread Thread-1 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/reloader.py", line 44, in run
<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'stat'
[2017-10-09 21:39:06 +0000] [179] [INFO] Booting worker with pid: 179
[2017-10-09 22:54:53 +0000] [29] [CRITICAL] WORKER TIMEOUT (pid:179)
[2017-10-09 22:54:53 +0000] [183] [INFO] Booting worker with pid: 183
[2017-10-10 02:10:52 +0000] [29] [CRITICAL] WORKER TIMEOUT (pid:183)
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/reloader.py", line 42, in run
    for filename in self.get_files():
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/reloader.py", line 30, in get_files
    for module in list(sys.modules.values())
AttributeError: 'NoneType' object has no attribute 'modules'

[2017-10-10 02:10:52 +0000] [187] [INFO] Booting worker with pid: 187
[2017-10-10 03:09:00 +0000] [29] [CRITICAL] WORKER TIMEOUT (pid:187)
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/reloader.py", line 42, in run
    for filename in self.get_files():
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/reloader.py", line 30, in get_files
    for module in list(sys.modules.values())
AttributeError: 'NoneType' object has no attribute 'modules'

[2017-10-10 03:09:00 +0000] [191] [INFO] Booting worker with pid: 191
[2017-10-10 07:40:51 +0000] [29] [CRITICAL] WORKER TIMEOUT (pid:191)
[2017-10-10 07:40:51 +0000] [195] [INFO] Booting worker with pid: 195
[2017-10-10 10:11:34 +0000] [29] [CRITICAL] WORKER TIMEOUT (pid:195)
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/reloader.py", line 42, in run
    for filename in self.get_files():
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/reloader.py", line 30, in get_files
    for module in list(sys.modules.values())
AttributeError: 'NoneType' object has no attribute 'modules'

[2017-10-10 10:11:34 +0000] [199] [INFO] Booting worker with pid: 199
[2017-10-10 13:03:13 +0000] [29] [INFO] Starting gunicorn 19.7.1
[2017-10-10 13:03:13 +0000] [29] [INFO] Listening at: http://127.0.0.1:8080 (29)
[2017-10-10 13:03:13 +0000] [29] [INFO] Using worker: sync
[2017-10-10 13:03:13 +0000] [37] [INFO] Booting worker with pid: 37
[2017-10-10 14:22:32 +0000] [27] [INFO] Starting gunicorn 19.7.1
[2017-10-10 14:22:32 +0000] [27] [INFO] Listening at: http://127.0.0.1:8080 (27)
[2017-10-10 14:22:32 +0000] [27] [INFO] Using worker: sync
[2017-10-10 14:22:33 +0000] [37] [INFO] Booting worker with pid: 37
[2017-10-10 14:33:49 +0000] [31] [INFO] Starting gunicorn 19.7.1
[2017-10-10 14:33:49 +0000] [31] [INFO] Listening at: http://127.0.0.1:8080 (31)
[2017-10-10 14:33:49 +0000] [31] [INFO] Using worker: sync
[2017-10-10 14:33:49 +0000] [41] [INFO] Booting worker with pid: 41
[2017-10-10 14:37:25 +0000] [29] [INFO] Starting gunicorn 19.7.1
[2017-10-10 14:37:25 +0000] [29] [INFO] Listening at: http://127.0.0.1:8080 (29)
[2017-10-10 14:37:25 +0000] [29] [INFO] Using worker: sync
[2017-10-10 14:37:25 +0000] [40] [INFO] Booting worker with pid: 40
[2017-10-10 14:53:04 +0000] [27] [INFO] Starting gunicorn 19.7.1
[2017-10-10 14:53:04 +0000] [27] [INFO] Listening at: http://127.0.0.1:8080 (27)
[2017-10-10 14:53:04 +0000] [27] [INFO] Using worker: sync
[2017-10-10 14:53:04 +0000] [38] [INFO] Booting worker with pid: 38
[2017-10-11 02:54:22 +0000] [31] [INFO] Starting gunicorn 19.7.1
[2017-10-11 02:54:22 +0000] [31] [INFO] Listening at: http://127.0.0.1:8080 (31)
[2017-10-11 02:54:22 +0000] [31] [INFO] Using worker: sync
[2017-10-11 02:54:22 +0000] [41] [INFO] Booting worker with pid: 41
[2017-10-11 05:09:32 +0000] [29] [INFO] Starting gunicorn 19.7.1
[2017-10-11 05:09:32 +0000] [29] [INFO] Listening at: http://127.0.0.1:8080 (29)
[2017-10-11 05:09:32 +0000] [29] [INFO] Using worker: sync
[2017-10-11 05:09:32 +0000] [39] [INFO] Booting worker with pid: 39
[2017-10-12 01:36:54 +0000] [32] [INFO] Starting gunicorn 19.7.1
[2017-10-12 01:36:54 +0000] [32] [INFO] Listening at: http://127.0.0.1:8080 (32)
[2017-10-12 01:36:54 +0000] [32] [INFO] Using worker: sync
[2017-10-12 01:36:54 +0000] [40] [INFO] Booting worker with pid: 40
[2017-10-12 02:12:17 +0000] [29] [INFO] Starting gunicorn 19.7.1
[2017-10-12 02:12:17 +0000] [29] [INFO] Listening at: http://127.0.0.1:8080 (29)
[2017-10-12 02:12:17 +0000] [29] [INFO] Using worker: sync
[2017-10-12 02:12:17 +0000] [39] [INFO] Booting worker with pid: 39
[2017-10-12 02:15:12 +0000] [32] [INFO] Starting gunicorn 19.7.1
[2017-10-12 02:15:12 +0000] [32] [INFO] Listening at: http://127.0.0.1:8080 (32)
[2017-10-12 02:15:12 +0000] [32] [INFO] Using worker: sync
[2017-10-12 02:15:12 +0000] [43] [INFO] Booting worker with pid: 43
[2017-10-12 02:40:05 +0000] [32] [CRITICAL] WORKER TIMEOUT (pid:43)
[2017-10-12 02:40:05 +0000] [48] [INFO] Booting worker with pid: 48
[2017-10-12 05:41:47 +0000] [27] [INFO] Starting gunicorn 19.7.1
[2017-10-12 05:41:47 +0000] [27] [INFO] Listening at: http://127.0.0.1:8080 (27)
[2017-10-12 05:41:47 +0000] [27] [INFO] Using worker: sync
[2017-10-12 05:41:47 +0000] [37] [INFO] Booting worker with pid: 37
[2017-10-12 07:51:32 +0000] [27] [CRITICAL] WORKER TIMEOUT (pid:37)
Exception in thread Thread-1 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/reloader.py", line 42, in run
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/reloader.py", line 30, in get_files
<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'modules'
[2017-10-12 07:51:39 +0000] [45] [INFO] Booting worker with pid: 45
[2017-10-12 07:58:23 +0000] [27] [INFO] Starting gunicorn 19.7.1
[2017-10-12 07:58:23 +0000] [27] [INFO] Listening at: http://127.0.0.1:8080 (27)
[2017-10-12 07:58:23 +0000] [27] [INFO] Using worker: sync
[2017-10-12 07:58:23 +0000] [38] [INFO] Booting worker with pid: 38
2017-10-12 07:58:24,948 [MainThread:140349449418496] [django.request:182] [base:get_response] [WARNING]- Not Found: /favicon.ico
